version: "3.7"

services:
  db:
    image: postgres
    env_file:
      - ./postgres.env
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./postgres.env
